/* Deterministic offline browser checks. Run with Playwright available on NODE_PATH.
 * The HTTP server serves this checkout; every API request is stubbed in the tab.
 * No production services, model calls, or data writes are used.
 */
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const http = require('node:http');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '../atlas/web');
const node = (id, dataset='fixture') => ({id,label:`Entity ${id}`,type:'Gene',properties:{harvest_dataset:dataset}});
const graph = (count=1400) => ({nodes:Array.from({length:count},(_,i)=>node(`n${i}`)),claims:[],evidence:[],sources:[],harvest:{next_offset:null}});
const state = {revision:1,nodes:[],claims:[],sources:[],jobs:[],model:{available:true},csrf_token:'fixture'};
const delay = ms => new Promise(resolve=>setTimeout(resolve,ms));
(async()=>{
 const server=http.createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://localhost').pathname;const file=path.join(root,pathname==='/explore'?'explore.html':pathname);const body=await fs.readFile(file);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');res.end(body);}catch(_){res.writeHead(404);res.end();}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const browser=await chromium.launch({headless:true,args:['--js-flags=--expose-gc','--enable-precise-memory-info','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream',...(process.env.ATLAS_DISABLE_WEBGL?['--disable-webgl']:[])]});
 const failures=[],passed=[];
 async function fixture(test,run,setup){
  if(process.env.ATLAS_TEST_FILTER&&!new RegExp(process.env.ATLAS_TEST_FILTER).test(test))return;
  const page=await browser.newPage({viewport:{width:1200,height:800},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const routes=new Map();
  await page.route('**/api/**',async route=>{const url=new URL(route.request().url());const custom=routes.get(url.pathname);if(custom)return custom(route,url);let body={};if(url.pathname==='/api/harvest/graph')body=graph();else if(url.pathname==='/api/research/state')body=state;else if(url.pathname==='/api/resolved/graph')body={...graph(4),nodes:[node('r0'),node('r1'),node('r2'),node('r3')]};else if(url.pathname==='/api/harvest/datasets')body={datasets:[{id:'1',label:'Dataset A'},{id:'2',label:'Dataset B'}]};else if(url.pathname==='/api/harvest/records')body={page:Number(url.searchParams.get('page')),total:150,limit:50,records:[{row:1,id:'record:1:1'}]};else if(url.pathname.endsWith('/search'))body={results:[]};else if(url.pathname==='/api/voice/status')body={available:false};await route.fulfill({json:body});});
  await page.route('**/graph.js',async route=>{let code=await fs.readFile(process.env.ATLAS_GRAPH_SCRIPT||path.join(root,'graph.js'),'utf8');if(process.env.ATLAS_PROFILE_ONLY)code=code.replace('  init();',`window.__profile={timings:{},frames:[]}; const measure=(name,fn)=>function(...args){const start=performance.now();try{return fn(...args);}finally{(window.__profile.timings[name]??=[]).push(performance.now()-start);}};drawGraph=measure('drawGraph',drawGraph);syncOverlay=measure('syncOverlay',syncOverlay);highlight=measure('highlight',highlight);nodeAt=measure('nodeAt',nodeAt);render=measure('render',render);window.__profile.idle=()=>{document.activeElement?.blur();idleAfter=0;};let prior=0;requestAnimationFrame(function sample(time){if(prior)window.__profile.frames.push(time-prior);prior=time;requestAnimationFrame(sample);});\n  init();`);await route.fulfill({contentType:'text/javascript',body:code.replace('  init();',`window.__graphTest={snapshot:()=>({view:{...view},selected,searchTerm,matches:[...searchMatches],dataMode,gesture:!!gesture,world:nodes.map(n=>[n.id,n.wx,n.wy,n.wz])}),append:()=>appendHarvestNode({id:'extra',label:'Extra',type:'Gene',properties:{harvest_dataset:'fixture'}}),compose:()=>composeGraph(),select,searchNodes,switchDataMode,loadHarvestRecords,loadHarvestGraph}; init();`)});});
  try{if(setup)await setup(page,routes);await page.goto(`http://127.0.0.1:${server.address().port}/explore`);await page.waitForFunction(()=>document.querySelector('#network').dataset.nodeCount==='1400'&&document.body.dataset.workspaceReady==='true');await run(page,routes);assert.deepEqual(errors,[],'no browser exceptions');passed.push(test);console.log(`PASS ${test}`);}catch(e){failures.push({test,error:e.message.slice(0,1200)});console.error(`FAIL ${test}: ${e.message.slice(0,1200)}`);}finally{await page.close();}
 }
 try{
 if(!process.env.ATLAS_ENDURANCE_ONLY&&!process.env.ATLAS_PROFILE_ONLY){
 await fixture('search remains global while viewing a resolved cluster',async(page,routes)=>{
  routes.set('/api/harvest/search',route=>route.fulfill({json:{results:[node('outside','other')]}}));
  routes.set('/api/harvest/graph',(route,url)=>route.fulfill({json:url.searchParams.get('focus')?{...graph(1),nodes:[node('outside','other')]}:graph()}));
  await page.evaluate(()=>window.__graphTest.switchDataMode('resolved'));
  await page.locator('#node-search').fill('outside');
  const result=page.locator('[data-node-id="outside"]');await result.waitFor();await result.click();
  await page.waitForFunction(()=>window.__graphTest.snapshot().selected==='outside');
  assert.equal(await page.evaluate(()=>window.__graphTest.snapshot().dataMode),'harvest');
  await page.locator('#chat-toggle').click();
  assert.equal(await page.locator('.chat-scope').innerText(),'GRIN2A / GRIN2B');
 });
 await fixture('append retains existing world positions',async page=>{const before=await page.evaluate(()=>window.__graphTest.snapshot().world);await page.evaluate(()=>window.__graphTest.append());const after=await page.evaluate(()=>window.__graphTest.snapshot().world.slice(0,-1));assert.deepEqual(after,before);});
 await fixture('graph refresh retains search highlighting',async page=>{await page.locator('#node-search').fill('Entity n12');const before=await page.evaluate(()=>window.__graphTest.snapshot().matches);await page.evaluate(()=>window.__graphTest.compose());assert.deepEqual(await page.evaluate(()=>window.__graphTest.snapshot().matches),before);});
 await fixture('scope switch clears stale selection and context',async page=>{await page.evaluate(()=>window.__graphTest.select('n1'));await page.evaluate(()=>window.__graphTest.switchDataMode('resolved'));assert.equal(await page.locator('#selection').isVisible(),false);assert.equal(await page.evaluate(()=>window.__graphTest.snapshot().selected),null);});
 await fixture('resize preserves zoom and centered world point',async page=>{await page.locator('#network').press('+');const before=await page.evaluate(()=>window.__graphTest.snapshot().view);await page.setViewportSize({width:1000,height:700});await page.waitForTimeout(100);const after=await page.evaluate(()=>window.__graphTest.snapshot().view);assert.equal(after.k,before.k);assert.ok(Math.abs((600-before.x)/before.k-(500-after.x)/after.k)<.001);});
 await fixture('empty dataset filter invalidates pending rows',async(page,routes)=>{routes.set('/api/harvest/records',async route=>{await delay(300);await route.fulfill({json:{page:0,total:1,limit:50,records:[{row:1,id:'record:1:1'}]}});});await page.evaluate(()=>document.querySelector('#harvest-browse').click());await page.waitForFunction(()=>document.querySelector('#harvest-dataset-select').options.length===2);await page.locator('#harvest-dataset-filter').fill('does-not-exist');await page.waitForTimeout(450);assert.equal(await page.locator('#harvest-record-list article').count(),0);assert.match(await page.locator('#harvest-record-status').innerText(),/No dataset/);});
 await fixture('dataset changed by filter starts at page zero',async page=>{await page.evaluate(()=>document.querySelector('#harvest-browse').click());await page.waitForFunction(()=>!document.querySelector('#harvest-record-next').disabled);await page.locator('#harvest-record-next').click();await page.waitForFunction(()=>document.querySelector('#harvest-record-status').textContent.includes('page 2'));await page.locator('#harvest-dataset-filter').fill('Dataset B');await page.waitForTimeout(150);assert.match(await page.locator('#harvest-record-status').innerText(),/page 1/);});
 await fixture('stale remote search does not cross graph scopes',async(page,routes)=>{routes.set('/api/harvest/search',async route=>{await delay(350);await route.fulfill({json:{results:[node('stale')]}});});await page.locator('#node-search').fill('absent');await page.waitForTimeout(260);await page.evaluate(()=>window.__graphTest.switchDataMode('resolved'));await page.waitForTimeout(450);assert.equal(await page.locator('[data-node-id="stale"]').count(),0);});
 await fixture('lost pointer capture releases graph gesture',async page=>{await page.mouse.move(1000,600);await page.mouse.down();await page.evaluate(()=>document.querySelector('#network').dispatchEvent(new PointerEvent('lostpointercapture',{pointerId:1})));assert.equal(await page.evaluate(()=>window.__graphTest.snapshot().gesture),false);await page.mouse.up();});
 await fixture('IME enter does not send chat',async(page,routes)=>{let sent=0;routes.set('/api/atlas/ask',async route=>{sent++;await route.fulfill({json:{status:'completed',outcome:{answer:{answer:'Test'}}}});});await page.locator('#chat-toggle').click();await page.locator('#question').fill('composing');await page.locator('#question').dispatchEvent('keydown',{key:'Enter',isComposing:true});await page.waitForTimeout(150);assert.equal(sent,0);});
 await fixture('temporary workspace refresh failure retains model route',async(page,routes)=>{routes.set('/api/research/state',route=>route.fulfill({status:503,json:{error:{message:'Temporary outage'}}}));await page.evaluate(()=>window.AtlasWorkspace.refresh());assert.equal(await page.evaluate(()=>window.AtlasWorkspace.active),true);});
 await fixture('completed ask preserves edits made while waiting',async(page,routes)=>{routes.set('/api/atlas/ask',async route=>{await delay(250);await route.fulfill({json:{status:'completed',outcome:{answer:{answer:'Fixture answer',sources:[]}}}});});await page.locator('#chat-toggle').click();await page.locator('#question').fill('original');await page.locator('#question').press('Enter');await page.locator('#question').fill('next draft');await page.waitForTimeout(400);assert.equal(await page.locator('#question').inputValue(),'next draft');assert.match(await page.locator('#chat-messages').innerText(),/Fixture answer/);});

 await fixture('interrupted job polling reconnects without another question',async(page,routes)=>{let submits=0,polls=0;routes.set('/api/atlas/ask',async route=>{submits++;await route.fulfill({json:{id:'job1',status:'running'}});});routes.set('/api/research/jobs/job1',async route=>{polls++;await route.fulfill(polls===1?{status:503,json:{error:{message:'Temporary network interruption'}}}:{json:{id:'job1',status:'completed',outcome:{answer:{answer:'Recovered answer'}}}});});await page.locator('#chat-toggle').click();await page.locator('#question').fill('question');await page.locator('#question').press('Enter');await page.getByText('Recovered answer',{exact:true}).waitFor();assert.equal(submits,1);assert.equal(polls,2);});
 await fixture('outdated workspace response cannot replace newer revision',async(page,routes)=>{let count=0;routes.set('/api/research/state',async route=>{const request=++count;await delay(request===1?300:20);await route.fulfill({json:{...state,revision:request===1?2:3,model:{available:request!==1}}});});await page.evaluate(()=>Promise.all([window.AtlasWorkspace.refresh(),window.AtlasWorkspace.refresh()]));assert.equal(await page.locator('#send-question').isDisabled(),false);});
 await fixture('public questions send selected node without query inflation',async(page,routes)=>{routes.set('/api/research/state',route=>route.fulfill({status:404,json:{}}));await page.reload();await page.waitForFunction(()=>document.body.dataset.workspaceReady==='false'&&!!document.querySelector('#network').dataset.nodeCount);let asked;routes.set('/api/ask',async(route,url)=>{asked=Object.fromEntries(url.searchParams);await route.fulfill({json:{answer:'Outside reviewed scope',claim_ids:[]}});});await page.evaluate(()=>window.__graphTest.select('n1'));await page.locator('#chat-toggle').click();await page.locator('#question').fill('Any conflicting evidence?');await page.locator('#question').press('Enter');await page.getByText('Outside reviewed scope',{exact:true}).waitFor();assert.deepEqual(asked,{q:'Any conflicting evidence?',node:'n1'});});
 await fixture('failed reload retains usable cached graph',async(page,routes)=>{routes.set('/api/harvest/graph',route=>route.fulfill({status:503,json:{}}));await page.evaluate(()=>document.querySelector('#harvest-reload').click());await page.waitForTimeout(150);await page.evaluate(()=>window.__graphTest.switchDataMode('resolved'));await page.evaluate(()=>window.__graphTest.switchDataMode('harvest'));assert.equal(await page.locator('#network').getAttribute('data-node-count'),'1400');assert.equal(await page.evaluate(()=>window.__graphTest.snapshot().dataMode),'harvest');});
 await fixture('new search cancels remote selection expansion before graph mutation',async(page,routes)=>{routes.set('/api/harvest/search',route=>route.fulfill({json:{results:[node('remote')]}}));routes.set('/api/harvest/graph',async route=>{await delay(350);await route.fulfill({json:{...graph(1),nodes:[node('remote')]}});});await page.locator('#node-search').fill('remote');await page.locator('[data-node-id="remote"]').waitFor();await page.locator('[data-node-id="remote"]').click();await page.locator('#node-search').fill('Entity n1');await page.waitForTimeout(500);assert.equal(await page.locator('#network').getAttribute('data-node-count'),'1400');assert.equal(await page.evaluate(()=>window.__graphTest.snapshot().selected),null);});
 await fixture('older resumed answer cannot replace latest follow-up context',async(page,routes)=>{let resumed=false;routes.set('/api/research/state',route=>route.fulfill({json:{...state,jobs:resumed?[]:[{id:'old-job',kind:'ask',status:'running'}]}}));routes.set('/api/research/jobs/old-job',async route=>{resumed=true;await delay(350);await route.fulfill({json:{status:'completed',outcome:{answer:{answer:'Older response',claim_ids:['older-claim']}}}});});const calls=[];routes.set('/api/atlas/ask',route=>{calls.push(route.request().postDataJSON());return route.fulfill({json:{status:'completed',outcome:{answer:{answer:'Newer response',claim_ids:['newer-claim']}}}});});await page.evaluate(()=>window.AtlasWorkspace.refresh());await page.locator('#chat-toggle').click();await page.locator('#question').fill('New question');await page.locator('#question').press('Enter');await page.getByText('Older response',{exact:true}).waitFor();await page.locator('#question').fill('Follow-up');await page.locator('#question').press('Enter');await page.waitForTimeout(100);assert.equal(calls.length,2);assert.deepEqual(calls[1].claim_ids,['newer-claim']);});
 await fixture('graph request timeout restores load controls',async(page,routes)=>{routes.set('/api/harvest/graph',async route=>{await delay(250);await route.fulfill({json:graph()}).catch(()=>{});});await page.evaluate(()=>{const original=window.setTimeout;window.setTimeout=(callback,ms,...args)=>original(callback,ms===30000?50:ms,...args);document.querySelector('#harvest-reload').click();});await page.waitForTimeout(150);assert.match(await page.locator('#harvest-status').innerText(),/timed out/);assert.equal(await page.locator('#harvest-reload').isDisabled(),false);assert.equal(await page.locator('#network').getAttribute('data-node-count'),'1400');});
 await fixture('late public answer cannot overwrite new selection context',async(page,routes)=>{routes.set('/api/research/state',route=>route.fulfill({status:404,json:{}}));await page.reload();await page.waitForFunction(()=>document.body.dataset.workspaceReady==='false'&&!!document.querySelector('#network').dataset.nodeCount);let calls=[];routes.set('/api/ask',async(route,url)=>{calls.push(Object.fromEntries(url.searchParams));await delay(calls.length===1?200:0);await route.fulfill({json:{answer:'Fixture response',claim_ids:['old-claim']}});});await page.locator('#chat-toggle').click();await page.locator('#question').fill('First question');await page.locator('#question').press('Enter');await page.evaluate(()=>window.__graphTest.select('n3'));await page.evaluate(()=>window.__graphTest.select(null));await page.waitForTimeout(300);await page.locator('#question').fill('What evidence supports this?');await page.locator('#question').press('Enter');await page.waitForTimeout(100);assert.equal(calls.length,2);assert.equal(calls[1].claim,undefined);});
 await fixture('cancelled transcription cannot change draft and releases microphone',async(page,routes)=>{routes.set('/api/voice/status',route=>route.fulfill({json:{available:true}}));let arrived=false;routes.set('/api/voice/transcribe',async route=>{arrived=true;await delay(300);await route.fulfill({json:{text:'Late words'}}).catch(()=>{});});await page.addInitScript(()=>{const original=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);window.__tracks=[];navigator.mediaDevices.getUserMedia=async constraints=>{const stream=await original(constraints);window.__tracks.push(...stream.getTracks());return stream;};});await page.reload();await page.locator('#chat-toggle').click();await page.waitForFunction(()=>!document.querySelector('#voice-button').disabled);await page.locator('#question').fill('Preserve draft');await page.locator('#voice-button').click();await page.waitForFunction(()=>document.querySelector('#voice-button').dataset.state==='recording');await page.waitForTimeout(350);await page.locator('#voice-button').click();await page.waitForTimeout(80);assert.ok(arrived);await page.locator('#cancel-recording').click();await page.waitForTimeout(400);assert.equal(await page.locator('#question').inputValue(),'Preserve draft');assert.ok(await page.evaluate(()=>window.__tracks.length>0&&window.__tracks.every(track=>track.readyState==='ended')));});
 await fixture('permission response arriving after voice cancel releases its stream',async(page,routes)=>{routes.set('/api/voice/status',route=>route.fulfill({json:{available:true}}));await page.addInitScript(()=>{window.__stopped=false;navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>{window.__grantMicrophone=()=>resolve({getTracks:()=>[{stop:()=>{window.__stopped=true;}}]});});});await page.reload();await page.locator('#chat-toggle').click();await page.waitForFunction(()=>!document.querySelector('#voice-button').disabled);await page.locator('#voice-button').click();await page.waitForFunction(()=>!!window.__grantMicrophone);await page.locator('#cancel-recording').click();await page.evaluate(()=>window.__grantMicrophone());await page.waitForFunction(()=>window.__stopped);assert.equal(await page.locator('#voice-button').getAttribute('data-state'),'idle');});
 await fixture('mobile pinch preserves world layout and releases gesture',async page=>{await page.setViewportSize({width:390,height:844});const before=await page.evaluate(()=>window.__graphTest.snapshot());const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:140,y:420,id:1},{x:240,y:420,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:100,y:420,id:1},{x:280,y:420,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const after=await page.evaluate(()=>window.__graphTest.snapshot());assert.ok(after.view.k>before.view.k*1.5);assert.equal(after.gesture,false);assert.equal(after.selected,null);assert.deepEqual(after.world,before.world);await page.locator('#node-search').fill('Entity n17');await page.locator('#node-search').press('Enter');assert.equal(await page.locator('#selection-name').innerText(),'Entity n17');});
 await fixture('unknown job status offers bounded reconnect without resubmission',async(page,routes)=>{let polls=0,posts=0;routes.set('/api/atlas/ask',route=>{posts++;return route.fulfill({json:{id:'odd-job',status:'running'}});});routes.set('/api/research/jobs/odd-job',route=>{polls++;return route.fulfill({json:{status:polls<=4?'unexpected':'completed',outcome:{answer:{answer:'Manual reconnect recovered'}}}});});await page.evaluate(()=>{const original=setTimeout;window.setTimeout=(fn,ms,...args)=>original(fn,[1200,2400,3600].includes(ms)?10:ms,...args);});await page.locator('#chat-toggle').click();await page.locator('#question').fill('Check job');await page.locator('#question').press('Enter');const retry=page.getByRole('button',{name:'Reconnect to this answer'});await retry.waitFor();assert.equal(polls,4);await retry.click();await page.getByText('Manual reconnect recovered',{exact:true}).waitFor();assert.equal(polls,5);assert.equal(posts,1);});
 await fixture('slow coverage requests do not block graph readiness',async page=>{await page.waitForFunction(()=>window.__ready,null,{timeout:250});assert.equal(await page.locator('#node-search').isDisabled(),false);},async(page,routes)=>{await page.addInitScript(()=>{window.__ready=false;window.addEventListener('atlas:ready',()=>{window.__ready=true;});});for(const endpoint of ['/api/harvest/status','/api/resolved/status'])routes.set(endpoint,async route=>{await delay(500);await route.fulfill({json:{}}).catch(()=>{});});});
 await fixture('initial fallback request times out with recovery message',async(page,routes)=>{routes.set('/api/harvest/graph',route=>route.fulfill({status:503,json:{}}));routes.set('/api/resolved/graph',route=>route.fulfill({status:503,json:{}}));routes.set('/api/graph',async route=>{await delay(300);await route.fulfill({json:graph()}).catch(()=>{});});await page.addInitScript(()=>{const original=setTimeout;window.setTimeout=(fn,ms,...args)=>original(fn,ms===30000?50:ms,...args);});await page.reload();await page.waitForFunction(()=>document.querySelector('#graph-status').textContent.includes('timed out'),null,{timeout:1000});assert.equal(await page.locator('#node-search').isDisabled(),true);routes.set('/api/harvest/graph',route=>route.fulfill({json:graph()}));await page.evaluate(()=>window.__graphTest.loadHarvestGraph());assert.equal(await page.locator('#node-search').isDisabled(),false);});
 await fixture('stale initial failure cannot disable a newer graph',async(page,routes)=>{let fallbackStarted=false;routes.set('/api/harvest/graph',route=>route.fulfill({status:503,json:{}}));routes.set('/api/resolved/graph',route=>route.fulfill({status:503,json:{}}));routes.set('/api/graph',async route=>{fallbackStarted=true;await delay(300);await route.abort();});await page.reload();while(!fallbackStarted)await delay(10);routes.set('/api/resolved/graph',route=>route.fulfill({json:graph()}));await page.evaluate(()=>window.__graphTest.switchDataMode('resolved'));await page.waitForTimeout(350);assert.equal(await page.locator('#network').getAttribute('data-node-count'),'1400');assert.equal(await page.locator('#node-search').isDisabled(),false);assert.equal(await page.locator('#chat-toggle').isDisabled(),false);});
 await fixture('WebGL context loss retains graph and controls',async page=>{
  await page.evaluate(()=>window.__graphTest.select('n17'));await page.locator('#network').press('+');await page.waitForTimeout(50);
  const before=await page.evaluate(()=>window.__graphTest.snapshot()),renderer=await page.locator('#graph-paint').getAttribute('data-renderer');
  if(renderer==='webgl'){
   assert.equal(await page.evaluate(()=>document.querySelector('#graph-paint').getContext('webgl').getError()),0);
   await page.evaluate(()=>document.querySelector('#graph-paint').getContext('webgl').getExtension('WEBGL_lose_context').loseContext());
   await page.waitForFunction(()=>document.querySelector('#graph-paint').dataset.renderer==='canvas');
  }
  const after=await page.evaluate(()=>window.__graphTest.snapshot());assert.deepEqual(after.world,before.world);assert.deepEqual(after.view,before.view);assert.equal(after.selected,before.selected);
  await page.waitForFunction(()=>{const canvas=document.querySelector('#graph-paint');if(canvas.dataset.renderer!=='canvas')return false;const pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;for(let i=3;i<pixels.length;i+=4)if(pixels[i]>0)return true;return false;});
  await page.locator('#node-search').fill('Entity n18');await page.locator('#node-search').press('Enter');assert.equal(await page.evaluate(()=>window.__graphTest.snapshot().selected),'n18');assert.equal(await page.locator('#network').getAttribute('data-node-count'),'1400');
 });
 }
 if(process.env.ATLAS_PROFILE_ONLY)await fixture('dense 10k rendering budget',async(page,routes)=>{
  const dense=JSON.parse(require('node:zlib').gunzipSync(await fs.readFile(path.resolve(root,'../../data/curated/hgnc_dense_snapshot.json.gz'))));routes.set('/api/harvest/graph',route=>route.fulfill({json:dense}));await page.evaluate(()=>window.__graphTest.loadHarvestGraph());await page.waitForFunction(()=>document.querySelector('#network').dataset.nodeCount==='10000');
  await page.emulateMedia({reducedMotion:'no-preference'});await page.evaluate(()=>{document.querySelector('#ambient-motion').checked=true;window.__profile.timings={};window.__profile.frames=[];window.__profile.idle();});await page.waitForTimeout(4000);
  const idle=await page.evaluate(()=>({timings:window.__profile.timings,frames:window.__profile.frames}));await page.evaluate(()=>{window.__profile.timings={};window.__profile.frames=[];});
  await page.mouse.move(1040,600);await page.mouse.down();for(let i=0;i<50;i++)await page.mouse.move(1040-i*10,600-i*3);await page.mouse.up();await page.mouse.wheel(0,-150);await page.waitForTimeout(600);
  const interaction=await page.evaluate(()=>({timings:window.__profile.timings,frames:window.__profile.frames}));
  const summary=values=>{const s=[...values].sort((a,b)=>a-b);return{samples:s.length,medianMs:+(s[Math.floor(s.length*.5)]||0).toFixed(3),p95Ms:+(s[Math.floor(s.length*.95)]||0).toFixed(3),maxMs:+(s.at(-1)||0).toFixed(3)};};
  const summarize=value=>({frames:summary(value.frames),timings:Object.fromEntries(Object.entries(value.timings).map(([k,v])=>[k,summary(v)]))});const report={renderer:await page.locator('#graph-paint').getAttribute('data-renderer'),nodes:10000,claims:dense.claims.length,targets:await page.locator('#nodes .net-node').count(),idle:summarize(idle),interaction:summarize(interaction)};console.log(JSON.stringify({profile:report}));if(process.env.ATLAS_PROFILE_REPORT)await fs.writeFile(process.env.ATLAS_PROFILE_REPORT,JSON.stringify(report,null,2)+'\n');
 });
 if(Number(process.env.ATLAS_ENDURANCE_SECONDS)>0)await fixture('dense 10k browser endurance',async(page,routes)=>{
  const dense=JSON.parse(require('node:zlib').gunzipSync(await fs.readFile(path.resolve(root,'../../data/curated/hgnc_dense_snapshot.json.gz'))));
  routes.set('/api/harvest/graph',route=>route.fulfill({json:dense}));await page.evaluate(()=>window.__graphTest.loadHarvestGraph());await page.waitForFunction(()=>document.querySelector('#network').dataset.nodeCount==='10000');
  const cdp=await page.context().newCDPSession(page);await cdp.send('Performance.enable');
  const originalWorld=JSON.stringify(await page.evaluate(()=>window.__graphTest.snapshot().world));
  const started=Date.now(),duration=Number(process.env.ATLAS_ENDURANCE_SECONDS)*1000,samples=[];let iterations=0,nextSample=0,lifecycle=false,pinchCycles=0,chatCycles=0,filterCycles=0;const extended=!!process.env.ATLAS_ENDURANCE_EXTENDED;
  while(Date.now()-started<duration){
   const i=iterations++;
   if(extended&&i%20===0){await page.setViewportSize({width:i%40===0?1200:390,height:i%40===0?800:844});await page.locator('#network').press('0');}
   const viewport=page.viewportSize(),x=Math.round(viewport.width*.84),y=Math.round(viewport.height*.7);
   await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x-60+(i%5)*10,y-50+(i%3)*10,{steps:3});await page.mouse.up();
   await page.locator('#node-search').fill(dense.nodes[i%dense.nodes.length].label);await page.locator('#node-search').press('Enter');await page.locator('#clear-selection').click();
   await page.mouse.move(x,y);await page.mouse.wheel(0,i%2?100:-100);
   if(extended&&i%40===20){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:140,y:420,id:1},{x:240,y:420,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:110,y:420,id:1},{x:270,y:420,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});pinchCycles++;}
   if(extended&&i%10===0){await page.locator('#chat-toggle').click();await page.locator('#question').fill('Draft preserved during Canvas endurance.');await page.locator('#chat-close').click();chatCycles++;}
   if(extended&&i%30===0){await page.evaluate(()=>document.querySelector('#harvest-browse').click());await page.locator('#harvest-dataset-filter').fill('does-not-exist');await page.locator('#harvest-dataset-filter').fill('Dataset A');await page.locator('#harvest-datasets-close').click();filterCycles++;}
   if(i%10===0)await page.evaluate(()=>window.__graphTest.compose());
   if(!extended&&i%30===0){await page.setViewportSize({width:i%60===0?1200:1180,height:800});await page.locator('#network').press('0');}
   if(!lifecycle&&i>=20){await cdp.send('Page.setWebLifecycleState',{state:'frozen'});await delay(250);await cdp.send('Page.setWebLifecycleState',{state:'active'});lifecycle=true;}
   if(Date.now()-started>=nextSample){
    await cdp.send('HeapProfiler.collectGarbage');const metrics=(await cdp.send('Performance.getMetrics')).metrics;const heap=metrics.find(m=>m.name==='JSHeapUsedSize')?.value;
    const targets=await page.locator('#nodes .net-node').count();assert.ok(targets<=40,'cleared dense scene must keep bounded DOM targets');assert.equal(await page.locator('#network').getAttribute('data-node-count'),'10000');assert.equal(Number(await page.locator('#network').getAttribute('data-claim-count')),dense.claims.length);assert.equal(JSON.stringify(await page.evaluate(()=>window.__graphTest.snapshot().world)),originalWorld,'world coordinates must remain fixed throughout endurance');
    samples.push({seconds:Math.round((Date.now()-started)/1000),iterations,heapBytes:heap,targets});nextSample+=60000;console.log(JSON.stringify({endurance:samples.at(-1)}));
   }
   await page.waitForTimeout(400);
  }
  await cdp.send('HeapProfiler.collectGarbage');const finalHeap=(await cdp.send('Performance.getMetrics')).metrics.find(m=>m.name==='JSHeapUsedSize')?.value;const baseline=samples[Math.min(1,samples.length-1)]?.heapBytes;
  assert.ok(!baseline||finalHeap<baseline*1.8+5e6,'post-GC heap should not grow without bound');
  const summary={seconds:Math.round((Date.now()-started)/1000),iterations,nodes:10000,claims:dense.claims.length,fixture:'data/curated/hgnc_dense_snapshot.json.gz',renderer:await page.locator('#graph-paint').getAttribute('data-renderer'),lifecycleSuspendResume:lifecycle,extendedInteractions:extended,pinchCycles,chatCycles,filterCycles,viewportPhases:extended?[{width:1200,height:800},{width:390,height:844}]:[{width:1200,height:800},{width:1180,height:800}],samples,finalHeapBytes:finalHeap,heapGrowthBytes:baseline?finalHeap-baseline:null};console.log(JSON.stringify({enduranceSummary:summary}));
  if(process.env.ATLAS_ENDURANCE_REPORT)await fs.writeFile(process.env.ATLAS_ENDURANCE_REPORT,JSON.stringify(summary,null,2)+'\n');
 });
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
 console.log(JSON.stringify({passed,failures},null,2));if(failures.length)process.exitCode=1;
})().catch(error=>{console.error(error);process.exitCode=1;});
