/* Offline proposal UI reliability checks. All inbox requests are intercepted;
 * this test never submits a live proposal. Requires Playwright on NODE_PATH. */
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const http=require('node:http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../atlas/web');
const receiptId='12345678-1234-4234-8234-123456789012';
const receipt={id:receiptId,status:'pending_review'};
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
(async()=>{
 const server=http.createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://localhost').pathname;const file=path.join(root,pathname==='/propose'?'propose.html':pathname);const body=await fs.readFile(file);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(body);}catch(_){res.writeHead(404);res.end();}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({headless:true});const passed=[],failures=[];
 async function test(name,run){const page=await browser.newPage(),errors=[];page.setDefaultTimeout(5000);page.on('pageerror',error=>errors.push(error.message));if(process.env.ATLAS_PROPOSAL_SCRIPT)await page.route('**/proposal.js',async route=>route.fulfill({contentType:'text/javascript',body:await fs.readFile(process.env.ATLAS_PROPOSAL_SCRIPT,'utf8')}));await page.route('**/api/**',route=>route.fulfill({status:503,json:{error:{message:'Offline fixture unavailable'}}}));try{await run(page);assert.deepEqual(errors,[]);passed.push(name);console.log(`PASS ${name}`);}catch(error){failures.push({name,error:error.message.slice(0,1500)});console.error(`FAIL ${name}: ${error.message.slice(0,1500)}`);}finally{await page.close();}}
 async function fill(page,name='Fixture gene'){await page.locator('#name').fill(name);await page.locator('#kind').selectOption('gene');await page.locator('#description').fill('A fixture description that must remain private.');}
 try{
  await test('malformed receipt cannot display saved confirmation',async page=>{for(const result of [{},{id:receiptId,status:'unknown'},{id:'not-a-uuid',status:'pending_review'},{id:'87654321-1234-4234-8234-123456789012',status:'pending_review'}]){await page.route('**/api/proposals/*',route=>route.fulfill({json:result}));await page.goto(`${base}/propose?receipt=${receiptId}`);await page.locator('#proposal-form').waitFor();assert.equal(await page.locator('#receipt').isVisible(),false);assert.match(await page.locator('#form-status').innerText(),/did not confirm/);}});
  await test('receipt fetch timeout returns usable form',async page=>{await page.addInitScript(()=>{const original=setTimeout;window.setTimeout=(fn,ms,...args)=>original(fn,ms===20000?50:ms,...args);});await page.route('**/api/proposals/*',async route=>{await delay(200);await route.fulfill({json:receipt}).catch(()=>{});});await page.goto(`${base}/propose?receipt=${receiptId}`);await page.waitForFunction(()=>document.querySelector('#form-status').textContent.includes('timed out'));assert.equal(await page.locator('#proposal-form').isVisible(),true);assert.equal(await page.locator('#receipt').isVisible(),false);});
  await test('pending proposal locks fields and failed save restores draft',async page=>{let posts=0;await page.route('**/api/proposals',async route=>{posts++;await delay(200);await route.fulfill({status:503,json:{error:{message:'Fixture save interrupted'}}});});await page.goto(`${base}/propose`);await fill(page);await page.locator('#submit-proposal').click();assert.equal(await page.locator('#name').isDisabled(),true);assert.equal(await page.locator('#description').isDisabled(),true);await page.evaluate(()=>document.querySelector('#proposal-form').requestSubmit());await page.waitForFunction(()=>document.querySelector('#form-status').textContent==='Fixture save interrupted');assert.equal(posts,1);assert.equal(await page.locator('#name').isDisabled(),false);assert.equal(await page.locator('#description').inputValue(),'A fixture description that must remain private.');});
  await test('same draft retries with same key after timeout and reload',async page=>{let requests=[];await page.addInitScript(()=>{const original=setTimeout;window.setTimeout=(fn,ms,...args)=>original(fn,ms===20000?80:ms,...args);});await page.route('**/api/proposals',async route=>{requests.push(route.request().postDataJSON());if(requests.length===1){await delay(200);await route.fulfill({json:receipt}).catch(()=>{});}else await route.fulfill({json:receipt});});await page.goto(`${base}/propose?entry=search`);await fill(page);await page.locator('#submit-proposal').click();await page.waitForFunction(()=>document.querySelector('#form-status').textContent.includes('timed out'));await page.reload();await fill(page);await page.locator('#submit-proposal').click();await page.locator('#receipt').waitFor();assert.equal(requests.length,2);assert.equal(requests[0].request_id,requests[1].request_id);assert.equal(await page.locator('#receipt-id').innerText(),`Reference: ${receiptId}`);const saved=await page.evaluate(()=>JSON.stringify({...sessionStorage}));assert.equal(saved.includes('Fixture gene'),false);assert.equal(saved.includes('description'),false);assert.equal(saved.includes('private'),false);});
  await test('edited draft receives a new idempotency key',async page=>{const requests=[];await page.route('**/api/proposals',route=>{requests.push(route.request().postDataJSON());return route.fulfill({status:503,json:{error:{message:'Retry fixture'}}});});await page.goto(`${base}/propose`);await fill(page);await page.locator('#submit-proposal').click();await page.waitForFunction(()=>document.querySelector('#form-status').textContent==='Retry fixture');await page.locator('#name').fill('Different fixture gene');await page.locator('#submit-proposal').click();await page.waitForFunction(()=>!document.querySelector('#submit-proposal').disabled);assert.equal(requests.length,2);assert.notEqual(requests[0].request_id,requests[1].request_id);});
  await test('blocked storage preserves safe in-page retry',async page=>{const requests=[];await page.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new DOMException('Denied','SecurityError');};Storage.prototype.setItem=()=>{throw new DOMException('Denied','SecurityError');};});await page.route('**/api/proposals',route=>{requests.push(route.request().postDataJSON());return route.fulfill(requests.length===1?{status:503,json:{error:{message:'Retry fixture'}}}:{json:receipt});});await page.goto(`${base}/propose`);await fill(page);await page.locator('#submit-proposal').click();await page.waitForFunction(()=>document.querySelector('#form-status').textContent==='Retry fixture');await page.locator('#submit-proposal').click();await page.locator('#receipt').waitFor();assert.equal(requests[0].request_id,requests[1].request_id);});
  await test('malformed successful POST retains form and draft',async page=>{await page.route('**/api/proposals',route=>route.fulfill({json:{id:receiptId,status:'unknown'}}));await page.goto(`${base}/propose`);await fill(page);await page.locator('#submit-proposal').click();await page.waitForFunction(()=>document.querySelector('#form-status').textContent.includes('did not confirm'));assert.equal(await page.locator('#proposal-form').isVisible(),true);assert.equal(await page.locator('#name').inputValue(),'Fixture gene');});
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
 console.log(JSON.stringify({passed,failures},null,2));if(failures.length)process.exitCode=1;
})().catch(error=>{console.error(error);process.exitCode=1;});
